/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentation;
import BLL.*;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author lsayh
 */
public class FmHoaDon extends javax.swing.JFrame {

    /**
     * Creates new form FmHoaDon
     */
    public FmHoaDon() {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FmHoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FmHoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FmHoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FmHoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        initComponents();
        setLocationRelativeTo(null);
        this.setVisible(true);
        showtable(null,0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GroupRadioChoose = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel(){
            ImageIcon icon = new ImageIcon("src/Presentation/Resources/16.png");
            public void paintComponent(Graphics g){
                Dimension d = getSize();
                g.drawImage(icon.getImage(), 0, 0, d.width, d.height, null);
                setOpaque(false);
                super.paintComponent(g);
            }
        };
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TbHoaDon = new javax.swing.JTable();
        BtnSearch = new javax.swing.JLabel();
        TxtSearchKey = new javax.swing.JTextField();
        RbInvoiceID = new javax.swing.JRadioButton();
        RbCustomer = new javax.swing.JRadioButton();
        RbEmployee = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setPreferredSize(new java.awt.Dimension(1366, 678));

        jLabel1.setFont(new java.awt.Font("Monotype Corsiva", 0, 72)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Invoice For Sales");
        jLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        TbHoaDon.setBackground(new java.awt.Color(0, 51, 102));
        TbHoaDon.setForeground(new java.awt.Color(255, 255, 255));
        TbHoaDon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Invoice ID", "Price", "Date", "Customer", "Employee"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Double.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TbHoaDon);

        BtnSearch.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BtnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Presentation/Resources/icons8-Search-30.png"))); // NOI18N
        BtnSearch.setToolTipText("Search");
        BtnSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnSearchMouseClicked(evt);
            }
        });

        TxtSearchKey.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        TxtSearchKey.setForeground(new java.awt.Color(204, 204, 204));
        TxtSearchKey.setText("Search");
        TxtSearchKey.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(204, 204, 204)));
        TxtSearchKey.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TxtSearchKeyMouseClicked(evt);
            }
        });

        RbInvoiceID.setBackground(new java.awt.Color(0, 102, 102));
        GroupRadioChoose.add(RbInvoiceID);
        RbInvoiceID.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        RbInvoiceID.setForeground(new java.awt.Color(204, 204, 204));
        RbInvoiceID.setSelected(true);
        RbInvoiceID.setText("Invoice ID");

        RbCustomer.setBackground(new java.awt.Color(0, 102, 102));
        GroupRadioChoose.add(RbCustomer);
        RbCustomer.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        RbCustomer.setForeground(new java.awt.Color(204, 204, 204));
        RbCustomer.setText("Customer");

        RbEmployee.setBackground(new java.awt.Color(0, 102, 102));
        GroupRadioChoose.add(RbEmployee);
        RbEmployee.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        RbEmployee.setForeground(new java.awt.Color(204, 204, 204));
        RbEmployee.setText("Employee");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Presentation/Resources/back.png"))); // NOI18N
        jLabel3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel3MouseMoved(evt);
            }
        });
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel3MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel3MousePressed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Presentation/Resources/user.png"))); // NOI18N
        jLabel11.setText("Admin");
        jLabel11.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel11MouseMoved(evt);
            }
        });
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel11MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(BtnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(RbInvoiceID)
                                .addGap(60, 60, 60)
                                .addComponent(RbCustomer)
                                .addGap(73, 73, 73)
                                .addComponent(RbEmployee))
                            .addComponent(TxtSearchKey, javax.swing.GroupLayout.PREFERRED_SIZE, 549, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(740, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 701, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(TxtSearchKey, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(RbEmployee)
                            .addComponent(RbInvoiceID)
                            .addComponent(RbCustomer))))
                .addGap(9, 9, 9)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 474, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //button thực hiện tìm kiếm theo từ khóa và option lấy từ radiobutton
    private void BtnSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnSearchMouseClicked
        int Option=0;
        if(RbInvoiceID.isSelected()) Option=1;
        if(RbCustomer.isSelected()) Option=2;
        if(RbEmployee.isSelected()) Option=3;
        showtable(TxtSearchKey.getText(), Option);
    }//GEN-LAST:event_BtnSearchMouseClicked

    private void jLabel3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseExited
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Presentation/Resources/back.png")));
    }//GEN-LAST:event_jLabel3MouseExited

    private void jLabel3MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseMoved
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Presentation/Resources/back1.png")));
    }//GEN-LAST:event_jLabel3MouseMoved
    //button thực hiện quay trờ lại form chính
    private void jLabel3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MousePressed
       new AdminHomepage()
               .setInfo(info);
        this.dispose();
    }//GEN-LAST:event_jLabel3MousePressed

    private void TxtSearchKeyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TxtSearchKeyMouseClicked
        TxtSearchKey.setText("");
    }//GEN-LAST:event_TxtSearchKeyMouseClicked

    private void jLabel11MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseExited
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Presentation/Resources/user.png")));
    }//GEN-LAST:event_jLabel11MouseExited

    private void jLabel11MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseMoved
    jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Presentation/Resources/user (2).png")));                                   // TODO add your handling code here:
    }//GEN-LAST:event_jLabel11MouseMoved

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        jLabel11.setText(info.getName());
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    //method hiện thị dữ liệu lên bảng TbHoaDon
    public void showtable(String Key, int Option){
        TableHoaDon model = new TableHoaDon((DefaultTableModel)TbHoaDon.getModel());
        if(Option!=0) TbHoaDon.setModel(model.model(Key,Option));
        else TbHoaDon.setModel(model.model(null,0));
        TbHoaDon.setAutoCreateRowSorter(true);
    }
    
    //biến lưu thông tin người đăng nhập và method để set thông tin người đăng nhập cho biến info
    //method này được gọi từ form khác
    private ClassLoginInfo info;
    public void setInfo(ClassLoginInfo info) {
        this.info = info;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BtnSearch;
    private javax.swing.ButtonGroup GroupRadioChoose;
    private javax.swing.JRadioButton RbCustomer;
    private javax.swing.JRadioButton RbEmployee;
    private javax.swing.JRadioButton RbInvoiceID;
    private javax.swing.JTable TbHoaDon;
    private javax.swing.JTextField TxtSearchKey;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
