/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentation;

import javax.swing.table.DefaultTableModel;
import BLL.*;
import java.awt.Dimension;
import java.awt.Graphics;
import java.math.BigDecimal;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import javafx.scene.chart.PieChart;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
/**
 *
 * @author lsayh
 */
public class FmNhapHoaDon extends javax.swing.JFrame {

    /**
     * Creates new form FmNhapHoaDon
     */
    public FmNhapHoaDon(String TenKH, String SDT, String DiaChi, String CMND) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FmNhapHoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FmNhapHoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FmNhapHoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FmNhapHoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        initComponents();
        setLocationRelativeTo(null);
        setVisible(true);
        if (!TenKH.equals("")) {
            TxtTenKH.setText(TenKH);
            TxtTenKH.setEditable(false);
            TxtDiaChi.setText(DiaChi);
            TxtDiaChi.setEditable(false);
            TxtSDT.setText(SDT);
            TxtCMND.setText(CMND);
            TxtCMND.setEditable(false);
            TxtTong.setText("0.0");
        }
        else {
            TxtSDT.setText(SDT);
            TxtTong.setText("0.0");
            TxtTenKH.setEnabled(true);
        }
        showtable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel(){
            ImageIcon icon = new ImageIcon("src/Presentation/Resources/19.jpg");
            public void paintComponent(Graphics g){
                Dimension d = getSize();
                g.drawImage(icon.getImage(), 0, 0, d.width, d.height, null);
                setOpaque(false);
                super.paintComponent(g);
            }
        }
        ;
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TbSanPham = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        TbGioHang = new javax.swing.JTable();
        BtnSearch = new javax.swing.JLabel();
        txtKeySearch = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        TxtSDT = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        TxtTenKH = new javax.swing.JTextField();
        TxtDiaChi = new javax.swing.JTextField();
        TxtCMND = new javax.swing.JTextField();
        TxtTenNhanVien = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        TxtTong = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("Customer");

        TbSanPham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item Name", "Amount", "Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TbSanPham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TbSanPhamMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TbSanPham);
        if (TbSanPham.getColumnModel().getColumnCount() > 0) {
            TbSanPham.getColumnModel().getColumn(1).setPreferredWidth(10);
        }

        TbGioHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item Name", "Amount", "Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TbGioHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TbGioHangMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(TbGioHang);

        BtnSearch.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BtnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Presentation/Resources/icons8-Search-30.png"))); // NOI18N
        BtnSearch.setToolTipText("123");
        BtnSearch.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                BtnSearchMouseMoved(evt);
            }
        });
        BtnSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnSearchMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnSearchMouseExited(evt);
            }
        });

        txtKeySearch.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtKeySearch.setForeground(new java.awt.Color(204, 204, 204));
        txtKeySearch.setText("Search");
        txtKeySearch.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(204, 204, 204)));
        txtKeySearch.setCaretColor(new java.awt.Color(204, 204, 204));
        txtKeySearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtKeySearchMouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Presentation/Resources/cart.png"))); // NOI18N
        jLabel4.setText("Your Cart");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("Phone Number");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("Identity Card");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setText("Address");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 204, 204));
        jLabel8.setText("Price");

        TxtSDT.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        TxtSDT.setForeground(new java.awt.Color(204, 204, 204));
        TxtSDT.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(204, 204, 204)));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 204, 204));
        jLabel9.setText("Cashier");

        TxtTenKH.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        TxtTenKH.setForeground(new java.awt.Color(204, 204, 204));
        TxtTenKH.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(204, 204, 204)));

        TxtDiaChi.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        TxtDiaChi.setForeground(new java.awt.Color(204, 204, 204));
        TxtDiaChi.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(204, 204, 204)));

        TxtCMND.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        TxtCMND.setForeground(new java.awt.Color(204, 204, 204));
        TxtCMND.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(204, 204, 204)));

        TxtTenNhanVien.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        TxtTenNhanVien.setForeground(new java.awt.Color(204, 204, 204));
        TxtTenNhanVien.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(204, 204, 204)));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Presentation/Resources/plus-button.png"))); // NOI18N
        jLabel3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel3MouseMoved(evt);
            }
        });
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel3MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel3MousePressed(evt);
            }
        });

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Presentation/Resources/back.png"))); // NOI18N
        jLabel10.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel10MouseMoved(evt);
            }
        });
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel10MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel10MousePressed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Presentation/Resources/user.png"))); // NOI18N
        jLabel11.setText("Admin");
        jLabel11.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel11MouseMoved(evt);
            }
        });
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel11MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel11MousePressed(evt);
            }
        });

        jLabel12.setBackground(new java.awt.Color(0, 102, 102));
        jLabel12.setFont(new java.awt.Font("Monotype Corsiva", 1, 72)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Create Invoice");
        jLabel12.setToolTipText("");

        TxtTong.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        TxtTong.setForeground(new java.awt.Color(204, 204, 204));
        TxtTong.setText("k");
        TxtTong.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(204, 204, 204)));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addGap(50, 50, 50)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 783, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(407, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(TxtSDT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(57, 57, 57)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(TxtDiaChi)
                                            .addComponent(TxtCMND)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(TxtTenKH, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                            .addComponent(TxtTenNhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(TxtTong, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(1, 1, 1))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(255, 255, 255)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(BtnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(txtKeySearch, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 634, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addGap(56, 56, 56))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)))
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtKeySearch, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnSearch))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TxtTenKH, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TxtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TxtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(45, 45, 45)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TxtCMND, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(50, 50, 50)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(TxtTenNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TxtTong, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(61, 61, 61)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGap(11, 11, 11)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    DecimalFormat df = new DecimalFormat("#");
    //sự kiện click trên table giỏ hàng
    //khi click thì dòng đang click sẽ mất đi hoặc số lượng -1 nếu số lượng >1
    //cập nhập lại tổng giá trong textfield
    private void TbGioHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TbGioHangMouseClicked
        int soluong=Integer.parseInt(String.valueOf(TbGioHang.getValueAt(TbGioHang.getSelectedRow(), 1)));
        double Gia1hang=Double.parseDouble(String.valueOf(TbGioHang.getValueAt(TbGioHang.getSelectedRow(), 2)));
        double gia1sp=Gia1hang/soluong;
        TbGioHang.setValueAt(Gia1hang-gia1sp, TbGioHang.getSelectedRow(), 2);
        TxtTong.setText(df.format(Double.parseDouble(TxtTong.getText())-gia1sp));
        if(soluong>1){
            TbGioHang.setValueAt(soluong-1, TbGioHang.getSelectedRow(), 1);
        }else if(soluong<=1){
            DefaultTableModel modelGiaHang = (DefaultTableModel)TbGioHang.getModel();
            modelGiaHang.removeRow(TbGioHang.getSelectedRow());
        }
    }//GEN-LAST:event_TbGioHangMouseClicked
    //sự kiện click trên table sản phẩm
    //khi click thì dòng đang click sẽ xuất hiện trong table giỏ hàng nếu chưa có trước đó
    //nếu không sẽ tăng số lượng lên 1
    private void TbSanPhamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TbSanPhamMouseClicked
        String TenSanPham = String.valueOf(TbSanPham.getValueAt(TbSanPham.getSelectedRow(), 0));
        int SoLuongSanPham = Integer.parseInt(String.valueOf(TbSanPham.getValueAt(TbSanPham.getSelectedRow(), 1)));
        boolean isfound=false;
        double Tong=0;          //biến cộng giá của tất cả các hàng của giỏ hàng
        for (int i = 0; i < TbGioHang.getRowCount(); i++) {         //vòng lặp duyệt tất cả các dòng của giỏ hàng
            int SoLuongGioHang = Integer.parseInt(String.valueOf(TbGioHang.getValueAt(i, 1)));
            if (TenSanPham.equals(String.valueOf(TbGioHang.getValueAt(i, 0)))&& SoLuongSanPham > SoLuongGioHang) {  //tìm thấy và số lượng ở giỏ hàng nhỏ hơn số lượng sản phẩm hiện còn trong kho
                isfound=true;           //biến đánh dấu đã tìm thấy
                TbGioHang.setValueAt(SoLuongGioHang + 1, i, 1);         //trường hợp giỏ hàng đã có hàng thì tăng số lượng sản phẩm
                int SoLuong1SpGiaHang=Integer.parseInt(String.valueOf(TbGioHang.getValueAt(i, 1))); //lấy số lượng 1 sản phẩm trong giỏ
                double GiaSp=Double.parseDouble(String.valueOf(TbSanPham.getValueAt(TbSanPham.getSelectedRow(), 2)));   //lấy giá sp
                TbGioHang.setValueAt(SoLuong1SpGiaHang*GiaSp,i,2);      //set giá trị soluong*gia1sp
            }
            Tong+=Double.parseDouble(String.valueOf(TbGioHang.getValueAt(i, 2)));       //tính tổng giá các dòng của giỏ hàng
            if(TenSanPham.equals(String.valueOf(TbGioHang.getValueAt(i, 0))))       //trường hợp đã bằng số lượng sản phẩm trong kho
            isfound=true;                       //dùng để phân biệt không tìm thấy và tìm thấy nhưng đã bằng số lượng trong kho
        }
        if (isfound == false) {             //trường hợp chưa có sản phẩm trong giỏ hàng thì tạo thêm dòng mới
            DefaultTableModel modelGiaHang = (DefaultTableModel) TbGioHang.getModel();
            double Gia = Double.parseDouble(String.valueOf(TbSanPham.getValueAt(TbSanPham.getSelectedRow(), 2)));
            int SoLuong = 1;        //lần đầu tiên cho số lượng là 1
            modelGiaHang.addRow(new Object[]{TenSanPham, SoLuong, Gia});
            Tong+=Double.parseDouble(String.valueOf(TbSanPham.getValueAt(TbSanPham.getSelectedRow(), 2)));  //tính tổng lượt đầu tiên
        }

        TxtTong.setText(df.format(Tong));
    }//GEN-LAST:event_TbSanPhamMouseClicked
    //button thực hiện liên tiếp các hoạt động theo thứ tự:
    //kiểm tra giỏ hàng là không trống --> kiểm tra khách hàng (nếu chưa có khách hàng thì tạo mới(insert) khách hàng)
    //--> tạo hóa đơn --> tạo chi tiết hóa đơn --> xuất hóa đơn ra file word --> reset table
    private void jLabel3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MousePressed
         if(TxtTenNhanVien.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Please choose a employee");
            return;
        }
        if(TbGioHang.getRowCount()==0){
            JOptionPane.showMessageDialog(rootPane, "Shopping cart is empty");
            return;
        }
        int idKH;
        if(TxtTenKH.isEditable()){
            if(TxtCMND.getText().length()==9)
                idKH = new CreateCus(TxtTenKH.getText(), TxtSDT.getText(), TxtCMND.getText(), TxtDiaChi.getText()).Action();
            else {
                JOptionPane.showMessageDialog(rootPane, "Identity Card must be contain 9 digits");
                return;
            }
            if(idKH<1){
                JOptionPane.showMessageDialog(rootPane, "Error to add a customer");
                return;
            }
        }
        int idHD;
        CreateHD createhd= new CreateHD(Float.parseFloat(TxtTong.getText()), TxtTenKH.getText(), TxtTenNhanVien.getText());
        idHD=createhd.Action();
        if(idHD>0)
        {
            String IDHD="HD"+idHD;
            for(int i=0;i<TbGioHang.getRowCount();i++){
                createhd.InsertChiTiet(IDHD,String.valueOf(TbGioHang.getValueAt(i, 0)),
                    Integer.parseInt(String.valueOf(TbGioHang.getValueAt(i, 1))),
                    Float.parseFloat(String.valueOf(TbGioHang.getValueAt(i, 2))));
            }
            
            JOptionPane.showMessageDialog(rootPane, "Thêm thành công");
            
            List<String> InfoKhachHang = new ArrayList<>();
            InfoKhachHang.add(TxtTenKH.getText());
            InfoKhachHang.add(TxtSDT.getText());
            InfoKhachHang.add(TxtCMND.getText());
            InfoKhachHang.add(TxtDiaChi.getText());
            InfoKhachHang.add(TxtTong.getText());
            List<List<String>> InfoHang = new ArrayList<List<String>>();
            for(int i=0;i<TbGioHang.getRowCount();i++){
                List<String> mylist = new ArrayList<>();
                mylist.add(String.valueOf(TbGioHang.getValueAt(i, 0)));
                mylist.add(String.valueOf(TbGioHang.getValueAt(i, 1)));
                BigDecimal soluong = new BigDecimal(String.valueOf(TbGioHang.getValueAt(i, 1)));
                BigDecimal ThanhTien = new BigDecimal(String.valueOf(TbGioHang.getValueAt(i, 2)));
                mylist.add(df.format(ThanhTien.divide(soluong)));
                mylist.add(df.format(TbGioHang.getValueAt(i, 2)));
                InfoHang.add(mylist);
            }
            try{
            new XuatHoaDon(IDHD, InfoKhachHang, InfoHang)
                    .Create();
            }catch(Exception ex){JOptionPane.showMessageDialog(rootPane, "Tạo hóa đơn không thành công");}
            showtable();
            resetTableGiaHang();
        }
        else JOptionPane.showMessageDialog(rootPane, "Không thành công");
    }//GEN-LAST:event_jLabel3MousePressed

    private void jLabel3MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseMoved
 jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Presentation/Resources/plus-button (1).png")));
    }//GEN-LAST:event_jLabel3MouseMoved

    private void jLabel3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseExited
 jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Presentation/Resources/plus-button.png")));
    }//GEN-LAST:event_jLabel3MouseExited

    private void jLabel10MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseMoved
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Presentation/Resources/back1.png")));
    }//GEN-LAST:event_jLabel10MouseMoved

    private void jLabel10MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseExited
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Presentation/Resources/back.png")));
    }//GEN-LAST:event_jLabel10MouseExited

    private void jLabel10MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MousePressed
        new AdminHomepage()
                .setInfo(info);
        this.dispose();
    }//GEN-LAST:event_jLabel10MousePressed

    private void txtKeySearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtKeySearchMouseClicked
       txtKeySearch.setText("");
    }//GEN-LAST:event_txtKeySearchMouseClicked

    private void jLabel11MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseMoved
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Presentation/Resources/user (2).png")));
        jLabel9.setVisible(true);
        jLabel8.setVisible(true);
    }//GEN-LAST:event_jLabel11MouseMoved

    private void jLabel11MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseExited
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Presentation/Resources/user.png")));
    }//GEN-LAST:event_jLabel11MouseExited

    private void jLabel11MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MousePressed
        jLabel9.setVisible(true);
        jLabel8.setVisible(true);
    }//GEN-LAST:event_jLabel11MousePressed

    private void BtnSearchMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnSearchMouseExited
        BtnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Presentation/Resources/icons8-Search-30.png")));
    }//GEN-LAST:event_BtnSearchMouseExited

    private void BtnSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnSearchMouseClicked
        resetTableSanPham();
    }//GEN-LAST:event_BtnSearchMouseClicked

    private void BtnSearchMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnSearchMouseMoved
        BtnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Presentation/Resources/search.png")));
    }//GEN-LAST:event_BtnSearchMouseMoved

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        jLabel11.setText(info.getName());
        TxtTenNhanVien.setText(info.getName());
    }//GEN-LAST:event_formWindowOpened
    //đổ thông tin về sản phẩm vào table sản phẩm
    public void showtable(){
        DefaultTableModel model=(DefaultTableModel)TbSanPham.getModel();
        int RowCount=model.getRowCount();
        for(int i=0;i<RowCount;i++){
            model.removeRow(RowCount-i-1);
        }
        TableHang modelhang = new TableHang((DefaultTableModel)TbSanPham.getModel());
        TbSanPham.setModel(modelhang.model(""));
    }
    //đổ thông tin về sản phẩm vào table sản phẩm được tìm kiếm theo tên
    public void resetTableSanPham(){
        DefaultTableModel model=(DefaultTableModel)TbSanPham.getModel();
        int RowCount=model.getRowCount();
        for(int i=0;i<RowCount;i++){
            model.removeRow(RowCount-i-1);
        }
        TableHang modelhang = new TableHang(model);
        TbSanPham.setModel(modelhang.model(txtKeySearch.getText()));
    }
    //làm trống giỏ hàng
    public void resetTableGiaHang(){
        DefaultTableModel model=(DefaultTableModel)TbGioHang.getModel();
        int RowCount=model.getRowCount();
        for(int i=0;i<RowCount;i++){
            model.removeRow(RowCount-i-1);
        }
        TbGioHang.setModel(model);
    }
    /**
     * @param args the command line arguments
     */
    
    private ClassLoginInfo info;

    public void setInfo(ClassLoginInfo info) {
        this.info = info;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BtnSearch;
    private javax.swing.JTable TbGioHang;
    private javax.swing.JTable TbSanPham;
    private javax.swing.JTextField TxtCMND;
    private javax.swing.JTextField TxtDiaChi;
    private javax.swing.JLabel TxtSDT;
    private javax.swing.JTextField TxtTenKH;
    private javax.swing.JLabel TxtTenNhanVien;
    private javax.swing.JLabel TxtTong;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField txtKeySearch;
    // End of variables declaration//GEN-END:variables
}
